version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest

workflows:
  build-and-test:
    jobs:
      - test

-run:
      name: run tests
      command: |
        . venv/bin/activate
        pytest -s -v --cov