version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest -s -v --conv

workflows:
  build-and-test:
    jobs:
      - test
